

THUMB_IDX = 4
INDEX_IDX = 8
MIDDLE_IDX = 12
RING_IDX = 16
PINKY_IDX = 20

FINGER_NAMES = ['Thumb', 'Index', 'Middle', 'Ring', 'Pinky']
FINGER_INDICES = [4, 8, 12, 16, 20]
FINGER_OUT_CUTOFF = 2.5e4

LEFT_CLICK_CUTOFF = 25
RIGHT_CLICK_CUTOFF = 25

SCROLL_VEL_CUTOFF = 5


MOUSE_X_SENS = 5.0
MOUSE_Y_SENS = 5.0