
"""One-off script that generated sounds/click.wav and sounds/key.wav --
not imported by the running program, just checked in so the sounds are
reproducible/tweakable without needing an external audio tool. Re-run it
(`python generate_sounds.py`) after editing the parameters below to
regenerate both files.

Key is a short, low-amplitude pure tone with a quick linear attack and an
eased-out decay (envelope**2, not a straight ramp) -- meant to be a light,
barely-there tick rather than an obvious "beep": no click/pop at the start
(the attack ramp) or abrupt cutoff at the end (the eased decay), and low
enough amplitude that it's felt more than heard, per the "light, not
intrusive or annoying" ask that started these.

Click has been through several redesigns, every one of them criticized:

1. A held 740Hz sine (~45ms) -- sounded like a system alert/error "bonk".
2. A noise burst plus a soft low sine "thud" underneath for body -- the
   thud read as heavy/harsh no matter how quiet it was mixed.
3. Noise burst plus a brief high pop resonance, no thud -- fixed the
   harshness, but noise-based sounds have an inherent "scratchy"/staticky
   texture (like radio static) that got *more* noticeable, not less, once
   the noise had to be loud enough to actually be heard.
4. A single tone sweeping downward in pitch (900Hz -> 320Hz) instead of
   holding one frequency -- turns out a downward pitch glide is *the*
   classic sci-fi laser/blaster sound effect. Should have been obvious in
   hindsight; wasn't, until it was pointed out.

Every one of those was a new synthesis idea trying to out-clever the
problem. Key, meanwhile -- a single held tone with a quick attack and an
eased-out decay, nothing else -- has never once been criticized for its
character, across this entire process; only its reliability was ever an
issue (a platform-specific playback bug, unrelated to how it sounds).
So click.wav is now generated by that exact same function, write_wav(),
just at different parameters (lower pitch, distinguishing it from key by
timbre/weight rather than by using a fundamentally different, riskier
technique). Boring on purpose.
"""

import math
import struct
import wave


def write_wav(path, freq, duration_s, amplitude, sample_rate=44100, attack_s=0.004, decay_s=None):
	n = int(sample_rate * duration_s)
	decay_s = decay_s or duration_s
	frames = []
	for i in range(n):
		t = i / sample_rate
		if t < attack_s:
			env = t / attack_s
		else:
			env = max(0.0, 1.0 - (t - attack_s) / decay_s)
			env = env ** 2
		sample = amplitude * env * math.sin(2 * math.pi * freq * t)
		frames.append(struct.pack('<h', int(sample * 32767)))

	with wave.open(path, 'w') as f:
		f.setnchannels(1)
		f.setsampwidth(2)
		f.setframerate(sample_rate)
		f.writeframes(b''.join(frames))


if __name__ == '__main__':
	# Click: same shape as key (see module docstring for why), just a
	# lower pitch and a touch more amplitude/duration -- reads as a
	# slightly heavier, more present "click" next to key's lighter "tick",
	# distinguished by pitch/weight, not by a different technique.
	write_wav('sounds/click.wav', freq=480, duration_s=0.05, amplitude=0.32, attack_s=0.003, decay_s=0.042)

	# Key: a light tone. Originally 32ms, which turned out to be too short
	# to reliably render at all -- most playback paths here (a fresh
	# process per play) have some device/process startup latency of their
	# own, and a clip that short can finish (or get clipped) before
	# playback has actually started, so it plays as silence even though
	# the file's samples are genuinely non-zero. 60ms -- still clearly the
	# shorter/lighter of the two sounds -- gives it enough of a window to
	# actually be heard.
	write_wav('sounds/key.wav', freq=1050, duration_s=0.06, amplitude=0.22, attack_s=0.003, decay_s=0.05)

	print('Wrote sounds/click.wav and sounds/key.wav')
